import js from '@eslint/js'
import stylistic from '@stylistic/eslint-plugin'
import importXPlugin from 'eslint-plugin-import-x'
import n from 'eslint-plugin-n'
import preferArrow from 'eslint-plugin-prefer-arrow-functions'
import promise from 'eslint-plugin-promise'
import unicorn from 'eslint-plugin-unicorn'
import globals from 'globals'

/** Formatting, control flow, functions and the merged Airbnb / Standard / recommended checks. */
const base = [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 'latest',
            globals: {
                ...globals.node,
            },
            sourceType: 'module',
        },
        plugins: {
            '@stylistic': stylistic,
            'import-x': importXPlugin,
            n,
            'prefer-arrow-functions': preferArrow,
            promise,
            unicorn,
        },
        rules: {
            '@stylistic/array-bracket-spacing': ['error', 'never'],
            '@stylistic/arrow-parens': ['error', 'as-needed'],
            '@stylistic/arrow-spacing': 'error',
            '@stylistic/block-spacing': ['error', 'always'],
            '@stylistic/brace-style': ['error', '1tbs', { allowSingleLine: true }],
            '@stylistic/comma-dangle': ['error', {
                arrays: 'always-multiline',
                exports: 'always-multiline',
                functions: 'always-multiline',
                imports: 'always-multiline',
                objects: 'always-multiline',
            }],
            '@stylistic/comma-spacing': 'error',
            '@stylistic/comma-style': ['error', 'last'],
            '@stylistic/computed-property-spacing': ['error', 'never'],
            '@stylistic/dot-location': ['error', 'property'],
            '@stylistic/eol-last': 'error',
            '@stylistic/function-call-spacing': ['error', 'never'],
            '@stylistic/generator-star-spacing': ['error', { after: true, before: false }],
            '@stylistic/indent': ['error', 4, { SwitchCase: 1 }],
            '@stylistic/key-spacing': 'error',
            '@stylistic/keyword-spacing': 'error',
            '@stylistic/linebreak-style': ['error', 'unix'],
            '@stylistic/lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
            '@stylistic/max-len': ['error', { code: 120, ignoreRegExpLiterals: true, ignoreUrls: true }],
            '@stylistic/new-parens': 'error',
            '@stylistic/no-extra-parens': ['error', 'functions'],
            '@stylistic/no-floating-decimal': 'error',
            '@stylistic/no-mixed-spaces-and-tabs': 'error',
            '@stylistic/no-multi-spaces': ['error', { ignoreEOLComments: true }],
            '@stylistic/no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 0 }],
            '@stylistic/no-tabs': 'error',
            '@stylistic/no-trailing-spaces': 'error',
            '@stylistic/no-whitespace-before-property': 'error',
            '@stylistic/object-curly-newline': ['error', {
                ObjectExpression: { consistent: true, multiline: true },
                ObjectPattern: { consistent: true, multiline: true },
            }],
            '@stylistic/object-curly-spacing': ['error', 'always'],
            '@stylistic/object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
            '@stylistic/operator-linebreak': ['error', 'after', { overrides: { ':': 'before', '?': 'before' } }],
            '@stylistic/padded-blocks': ['error', 'never'],
            '@stylistic/padding-line-between-statements': [
                'error',
                { blankLine: 'always', next: '*', prev: 'import' },
                { blankLine: 'never', next: 'import', prev: 'import' },
            ],
            '@stylistic/quote-props': ['error', 'as-needed'],
            '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
            '@stylistic/rest-spread-spacing': ['error', 'never'],
            '@stylistic/semi': ['error', 'never', { beforeStatementContinuationChars: 'never' }],
            '@stylistic/semi-spacing': 'error',
            '@stylistic/space-before-blocks': 'error',
            '@stylistic/space-before-function-paren': ['error', {
                anonymous: 'always',
                asyncArrow: 'always',
                named: 'never',
            }],
            '@stylistic/space-in-parens': ['error', 'never'],
            '@stylistic/space-infix-ops': 'error',
            '@stylistic/space-unary-ops': ['error', { nonwords: false, words: true }],
            '@stylistic/spaced-comment': ['error', 'always', {
                block: { balanced: true, exceptions: ['*'] },
                line: { markers: ['/'] },
            }],
            '@stylistic/switch-colon-spacing': 'error',
            '@stylistic/template-curly-spacing': ['error', 'never'],
            '@stylistic/template-tag-spacing': ['error', 'never'],
            '@stylistic/wrap-iife': ['error', 'outside'],
            '@stylistic/yield-star-spacing': ['error', 'after'],
            'array-callback-return': ['error', { allowImplicit: true }],
            'arrow-body-style': ['error', 'as-needed'],
            camelcase: 'off',
            'class-methods-use-this': 'error',
            'consistent-return': 'error',
            curly: ['error', 'multi-line'],
            'default-case': 'error',
            'default-case-last': 'error',
            'default-param-last': 'error',
            'dot-notation': 'error',
            eqeqeq: ['error', 'always', { null: 'ignore' }],
            'grouped-accessor-pairs': 'error',
            'guard-for-in': 'off',
            'import-x/export': 'error',
            'import-x/extensions': ['error', 'ignorePackages'],
            'import-x/first': 'error',
            'import-x/newline-after-import': 'error',
            'import-x/no-absolute-path': 'error',
            'import-x/no-amd': 'error',
            'import-x/no-cycle': 'error',
            'import-x/no-duplicates': 'error',
            'import-x/no-dynamic-require': 'error',
            'import-x/no-mutable-exports': 'error',
            'import-x/no-named-as-default': 'error',
            'import-x/no-named-as-default-member': 'error',
            'import-x/no-named-default': 'error',
            'import-x/no-self-import': 'error',
            'import-x/no-useless-path-segments': 'error',
            'import-x/no-webpack-loader-syntax': 'error',
            'import-x/prefer-default-export': 'error',
            'max-classes-per-file': ['error', 1],
            'n/handle-callback-err': ['error', '^(err|error)$'],
            'n/no-callback-literal': 'error',
            'n/no-deprecated-api': 'error',
            'n/no-exports-assign': 'error',
            'n/no-new-require': 'error',
            'n/no-path-concat': 'error',
            'n/process-exit-as-throw': 'error',
            'new-cap': ['error', { capIsNew: false, newIsCap: true, properties: true }],
            'no-array-constructor': 'error',
            'no-bitwise': 'off',
            'no-caller': 'error',
            'no-console': 'warn',
            'no-constructor-return': 'error',
            'no-else-return': ['error', { allowElseIf: false }],
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-label': 'error',
            'no-implied-eval': 'error',
            'no-iterator': 'error',
            'no-label-var': 'error',
            'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
            'no-lone-blocks': 'error',
            'no-lonely-if': 'error',
            'no-loop-func': 'error',
            'no-multi-assign': 'off',
            'no-multi-str': 'error',
            'no-nested-ternary': 'off',
            'no-new': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-object-constructor': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': ['error', { props: true }],
            'no-plusplus': 'off',
            'no-promise-executor-return': 'error',
            'no-proto': 'error',
            'no-restricted-globals': ['error',
                { message: 'Use Number.isFinite instead.', name: 'isFinite' },
                { message: 'Use Number.isNaN instead.', name: 'isNaN' },
            ],
            'no-restricted-syntax': ['error',
                {
                    message: 'Define it first, then `export default name` at the end.',
                    selector: 'ExportDefaultDeclaration > ' +
                        ':matches(ClassDeclaration, FunctionDeclaration, NewExpression)',
                },
                {
                    message: 'No `= undefined` defaults: give the real default or none.',
                    selector: 'AssignmentPattern > Identifier.right[name="undefined"]',
                },
                {
                    message: 'Check the flag itself: `if (flag)`.',
                    selector: 'IfStatement > BinaryExpression.test[operator="==="] > Literal.right[raw="true"]',
                },
            ],
            'no-return-assign': 'off',
            'no-script-url': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'off',
            'no-shadow': 'error',
            'no-template-curly-in-string': 'error',
            'no-throw-literal': 'error',
            'no-undef-init': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unneeded-ternary': ['error', { defaultAssignment: false }],
            'no-unreachable-loop': 'error',
            'no-unused-expressions': 'off',
            'no-use-before-define': ['error', { classes: false, functions: false, variables: false }],
            'no-useless-call': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-concat': 'error',
            'no-useless-constructor': 'error',
            'no-useless-rename': 'error',
            'no-useless-return': 'error',
            'no-var': 'error',
            'no-void': 'error',
            'object-shorthand': ['error', 'always', { avoidQuotes: true }],
            'one-var': ['error', 'never'],
            'operator-assignment': ['error', 'always'],
            'prefer-arrow-callback': 'error',
            'prefer-arrow-functions/prefer-arrow-functions': ['error', {
                allowNamedFunctions: false,
                classPropertiesAllowed: false,
                returnStyle: 'implicit',
            }],
            'prefer-const': ['error', { destructuring: 'all' }],
            'prefer-destructuring': ['error', { array: false, object: true }],
            'prefer-exponentiation-operator': 'error',
            'prefer-numeric-literals': 'error',
            'prefer-promise-reject-errors': 'error',
            'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'promise/param-names': 'error',
            radix: 'error',
            'symbol-description': 'error',
            'unicode-bom': ['error', 'never'],
            'unicorn/numeric-separators-style': ['error', {
                binary: { onlyIfContainsSeparator: true },
                hexadecimal: { onlyIfContainsSeparator: true },
                number: { groupLength: 3, minimumDigits: 5 },
                octal: { onlyIfContainsSeparator: true },
                onlyIfContainsSeparator: false,
            }],
            yoda: 'error',
        },
    },
]

export default base
